# These are the settings to do with the crates.

# If you can view the possible rewards of the crate on left click.
view-on-left-click: true
# The time between each saving of the crate. Supported timespans are milliseconds, seconds, minutes, hours and days.
# First backup will be run 30 minutes after the server starts.
backup-interval: 30 minutes
# Whether to drop the crate item when it is broken.
drop-on-break: false

# Settings with the expressions:
# • <crate> = The id of a crate.
# • <crate-name> = The name of a crate.
crate-inventory-name: §e<crate-name> Crate §8(§7<crate>§8)